PlacementPortal/urls.py
from django.urls import path
from .views import *
from .api import *

app_name = "PlacementPortal"

urlpatterns = [

    path('login/', LoginUser.as_view(), name="login_url"),
    path('logout/', logout_user, name="logout"),

    path('department/<int:dept_id>/student/<int:pk>/marks/', MarkList.as_view(), name="student_marks"),
    path('department/<int:dept_id>/student/<int:pk>/contact/', ContactDetail.as_view(), name="student_contact"),

    path('department/', DepartmentList.as_view(), name="department_list"),
    path('department/<int:dept_id>/student/', DepartmentStudentList.as_view(), name="department_student_list"),
    path('department/<int:dept_id>/student/<int:pk>/edit', DepartmentStudentEdit.as_view(),
         name="department_student_edit"),
    path('department/<int:pk>/delete/', DepartmentDelete.as_view(), name="department_delete"),
    path('department/<int:pk>/edit/', DepartmentUpdate.as_view(), name="department_update"),
    path('department/add/', DepartmentCreate.as_view(), name="department_add"),

    path('home/', Home.as_view(), name="home"),
    path('', LoginUser.as_view(), name="login"),

    path('studentUpload/', studentUpload, name="student_file_upload"),
    path('marksUpload/', marksUpload, name="marks_file_upload"),
    path('query/', QueryDb.as_view(), name='select_query'),



    # api urls
    path('api/', StudentListView.as_view(), name="api_student_list"),
    path('api/<str:htno>/', StudentDetailView.as_view(), name="api_student_detail"),
]



agi-demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("PlacementPortal.urls")),
    path('studentPortal/', TemplateView.as_view(template_name="StudentPortal/index.html")),
]

PlacementPortal/models.py
from django.db import models


class Contact(models.Model):
    email = models.EmailField()
    phone_number = models.CharField(max_length=10)
    address = models.TextField()
    guardian_parent_name = models.CharField(max_length=80)
    guardian_parent_contact = models.CharField(max_length=10)
    guardian_parent_profession = models.CharField(max_length=80)

    def __str__(self):
        return self.email


class Department(models.Model):
    name = models.CharField(max_length=100)
    acronym = models.CharField(max_length=100)

    def __str__(self):
        return self.acronym


class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    hall_ticket_number = models.CharField(max_length=100, unique=True)
    gender = models.BooleanField()
    caste = models.CharField(max_length=100)
    career_goal = models.TextField()

    tenth_marks = models.IntegerField()
    inter_marks = models.IntegerField()

    btech_marks = models.IntegerField(default=-1)
    backlogs = models.IntegerField(default=-1)

    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name + " - " + self.hall_ticket_number


class Marks(models.Model):
    subject_code = models.CharField(max_length=15)
    subject_name = models.CharField(max_length=100)
    internal_marks = models.IntegerField()
    external_marks = models.IntegerField()
    total_marks = models.IntegerField()
    result = models.CharField(max_length=10)

    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="marks")

    def __str__(self):
        return self.subject_code+" "+str(self.external_marks)+" "+self.result



PlacementPortal/forms/contact.py
from django import forms
from PlacementPortal.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = []

PlacementPortal/api/views.py
from rest_framework.generics import RetrieveAPIView, ListAPIView

from PlacementPortal.models import Student

from .serializers import StudentSerializer


class StudentListView(ListAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer


class StudentDetailView(RetrieveAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer
    lookup_field = "hall_ticket_number"
    lookup_url_kwarg = "htno"


PlacementPortal/views/contact.py
from django.views.generic import DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin


from PlacementPortal.models import Contact, Student


class ContactDetail(LoginRequiredMixin, DetailView):
    model = Contact
    template_name = "PlacementPortal/contact_detail.html"
    context_object_name = "contact"

    def get_context_data(self, **kwargs):
        context = super(ContactDetail, self).get_context_data(**kwargs)
        student_detail = Student.objects.get(pk=self.kwargs['pk'])
        student_contact = Contact.objects.get(student__id=self.kwargs['pk'])
        context.update(
            {
                'student_detail': student_detail,
                'student_contact': student_contact
            }
        )
        return context




PlacementPortal/views/department.py
from django.views.generic import ListView, DeleteView, CreateView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from PlacementPortal.models import Department, Student
from PlacementPortal.forms import DepartmentForm, StudentForm, ContactForm


class DepartmentList(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Department
    template_name = "PlacementPortal/department_list.html"


class DepartmentDelete(LoginRequiredMixin, DeleteView):
    login_url = "/login/"
    slug_url_kwarg = 'dept_id'
    model = Department
    template_name = "PlacementPortal/department_delete.html"
    success_url = reverse_lazy("PlacementPortal:home")


class DepartmentCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Department
    template_name = "PlacementPortal/department_form.html"
    form_class = DepartmentForm
    success_url = reverse_lazy("PlacementPortal:department_list")


class DepartmentUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Department
    template_name = "PlacementPortal/department_form.html"
    form_class = DepartmentForm
    success_url = reverse_lazy("PlacementPortal:department_list")


class DepartmentStudentList(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    model = Student
    template_name = "PlacementPortal/student_list.html"

    def get_object(self, queryset=None):
        object = Student.objects.values(
            "id",
            "full_name",
            "hall_ticket_number",
            "department__acronym",
            "date_of_birth",
            "gender",
            "caste",
            "tenth_marks",
            "inter_marks",
            "department_id",
            "btech_marks",
            "backlogs"
        ).filter(department_id=self.kwargs.get('dept_id'))
        return object

    def get_context_data(self, **kwargs):
        context = super(DepartmentStudentList, self).get_context_data(**kwargs)
        student_list = context.get('object')
        context.update(
            {
                'student_list': student_list
            }
        )
        return context


class DepartmentStudentEdit(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Student
    template_name = "PlacementPortal/student_form.html"
    form_class = StudentForm
    success_url = reverse_lazy("PlacementPortal:department_list")

    def get_context_data(self, **kwargs):
        context = super(DepartmentStudentEdit, self).get_context_data(**kwargs)
        student_form = context.get("form")
        contact_form = ContactForm(instance=self.get_object().contact)
        context.update(
            {
                'student_form': student_form,
                'contact_form': contact_form,
            }
        )
        return context

    def post(self, request, *args, **kwargs):
        student = Student.objects.get(pk=kwargs.get('pk'))

        getGenderUpdate = request.POST['gender']

        if int(getGenderUpdate) == 1:
            student.gender = True
        else:
            student.gender = False

        student_form = StudentForm(request.POST, instance=student)
        contact_form = ContactForm(request.POST, instance=student.contact)

        contact_form.save()
        student_form.save()

        return redirect("PlacementPortal:department_list")

PlacementPortal/views/marks.py
from django.views.generic import ListView

from PlacementPortal.models import Marks, Student


class MarkList(ListView):
    context_object_name = "marks_list"
    template_name = "PlacementPortal/marks_list.html"

    def get_queryset(self):
        queryset = Marks.objects.filter(student__id=self.kwargs['pk'])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MarkList, self).get_context_data(**kwargs)
        context['student'] = Student.objects.get(pk=self.kwargs['pk'])
        return context



PlacementPortal/views/query_db.py
from PlacementPortal.forms import GetStudentDetails
from django.shortcuts import render
from django.views import View
from PlacementPortal.models import *
from django.http import HttpResponse
import pandas as pd
from io import BytesIO as IO


class QueryDb(View):

    def get(self, request):
        print("abcd")
        form = GetStudentDetails()
        return render(request, "PlacementPortal/query_form.html", context={'form': form})

    def post(self, request, *args, **kwargs):
        form = GetStudentDetails(request.POST)
        if form.is_valid():

            data = form.cleaned_data

            gender = data['gender']
            tenth = data['tenth']
            inter = data['inter']
            btech = data['btech']
            backlogs = data['backlogs']
            caste = data['caste']
            department = data['department']

            index = 0
            for i in gender:
                if i == '0':
                    gender = [True, False]
                    break
                elif i == 'Male':
                    gender[index] = True
                elif i == 'Female':
                    gender[index] = False
                index = index + 1

            for i in department:
                if i == '0':
                    department = ['CSE', 'ECE', 'CIVIL', 'MECH', 'IT', 'CHEM']
                    break

            for i in caste:
                if i == '0':
                    caste = ['OC', 'SC', 'ST', 'BC']
                    break

            data_res = Student.objects.values("pk", "first_name", "last_name", "hall_ticket_number", "gender",
                                              'date_of_birth',
                                              "backlogs", "caste", "tenth_marks", "department__acronym",
                                              "inter_marks", "btech_marks").order_by("pk").filter(
                inter_marks__gte=inter, btech_marks__gte=btech, tenth_marks__gte=tenth,
                backlogs__lte=backlogs, gender__in=gender,
                department__acronym__in=department)

            res_arr = []
            res_arr.append(
                ['Name', 'Hall Ticket Number', 'Department', 'DOB', 'Gender', 'Caste', 'Tenth %', 'Inter %', 'Btech %',
                 'Backlogs'])

            index = 0
            for item in data_res:
                name = data_res[index]['first_name'] + data_res[index]['last_name']
                hallticket = data_res[index]['hall_ticket_number']
                dept = data_res[index]['department__acronym']
                dob = str(data_res[index]['date_of_birth'])
                gender = None
                if data_res[index]['gender']:
                    self.gender = 'Male'
                else:
                    self.gender = 'Female'

                caste = data_res[index]['caste']
                tenth = data_res[index]['tenth_marks']
                inter = data_res[index]['inter_marks']
                btech = data_res[index]['btech_marks']
                backlogs = data_res[index]['backlogs']

                res_arr.append([name, hallticket, dept, dob, self.gender, caste, tenth, inter, btech, backlogs])
                index = index + 1
            df_output = pd.DataFrame(res_arr)
            excel_file = IO()

            xlwriter = pd.ExcelWriter(excel_file, engine='xlsxwriter')
            df_output.to_excel(xlwriter, 'sheetname')

            xlwriter.save()
            xlwriter.close()
            excel_file.seek(0)
            response = HttpResponse(excel_file.read(),
                                    content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            response['Content-Disposition'] = 'attachment; filename=myfile.xlsx'

            return response

PlacementPortal/views/settings.py
"""
Django settings for agi-demo project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')^0*&0uuo2cd7dg9vv%rb0n&5-c03(^!+d$i-3@$#5!+(1$s!r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['13.127.240.174', "127.0.0.1", 'localhost', "ec2-13-232-139-244.ap-south-1.compute.amazonaws.com:8080"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # project dependencies
    'PlacementPortal',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    # project dependencies
    'corsheaders.middleware.CorsMiddleware',

    # 'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agi-demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agi-demo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dbname',
        'HOST': 'mydbinstance.cojgcf4npzmk.ap-south-1.rds.amazonaws.com',
        'USER': "uname",
        'PASSWORD': "pword1234"
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

CORS_ORIGIN_WHITELIST = (
    'http://ec2-13-127-240-174.ap-south-1.compute.amazonaws.com:8080/'
)

templates/PlacementPortal/contact_detail.html
{% extends "base.html" %}
{% block content %}
    <br>
    <h4>{{ student_detail.full_name }}</h4>
    <h4>{{ student_detail.hall_ticket_number }}</h4>
    <br>
    <table class="table table-hover table-bordered">
        <tr>
            <th>Email</th>
            <td>{{ student_contact.email }}</td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td>{{ student_contact.phone_number }}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td>{{ student_contact.address }}</td>
        </tr>
        <tr>
            <th>Guardian/parent Name</th>
            <td>{{ student_contact.guardian_parent_name }}</td>
        </tr>
        <tr>
            <th>Guardian/parent Contact</th>
            <td>{{ student_contact.guardian_parent_contact }}</td>
        </tr>
        <tr>
            <th>Guardian/parent Profession</th>
            <td>{{ student_contact.guardian_parent_profession }}</td>
        </tr>
    </table>
{% endblock content %}

templates/PlacementPortal/department_delete.html
{% extends "base.html" %}

{% block content %}
    <div style="">
        <br>
        <br>
        <form method="post" class="form-control">{% csrf_token %}
            <p style="color: red;" class="form-control">Are you sure you want to delete "{{ object.name }}"?</p>
            <p style="color: red;" class="form-control">All the {{ object.acronym }} students will be deleted.</p>
            <input class="btn-danger form-control" type="submit" value="Confirm"/>
        </form>
    </div>

{% endblock content %}

templates/PlacementPortal/department_form.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <form action="" method="POST" class="form-control">
        {% csrf_token %}
        {{ form }}
        <br>
        <input class="btn-default" type="submit" value="Submit"/>
    </form>
{% endblock content%}

templates/PlacementPortal/department_list.html
{% extends "base.html" %}

{% block content %}
    <br>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Department Name</th>
            <th>Acronym</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for department in department_list %}
            <tr>
                <td>{{ department.id }}</td>
                <td><a href="{% url "PlacementPortal:department_student_list" department.id %}">{{ department.name }}</a></td>
                <td>{{ department.acronym }}</td>
                <td>
                    <a href="{% url "PlacementPortal:department_update" department.id %}">Edit</a>
                </td>
                <td>
                    <a href="{% url "PlacementPortal:department_delete" department.id %}">Delete</a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'PlacementPortal:department_add' %}">+ Add Department</a>

{% endblock %}

templates/PlacementPortal/marks_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/PlacementPortal/marks_list.html
{% extends "base.html" %}

{% block content %}
    <br>
    <h4>{{ student.full_name }} - {{ student.hall_ticket_number }}</h4>
    <br>
        <table class="table table-bordered">
        <thead>
        <tr>
            <th>Subject Code</th>
            <th>Subject Name</th>
            <th>Internal Marks</th>
            <th>External Marks</th>
            <th>Total</th>
            <th>Result</th>
        </tr>
        </thead>
        <tbody>
        {% for marks in marks_list %}
            <tr>
                <td>{{ marks.subject_code }}</td>
                <td>{{ marks.subject_name }}</td>
                <td>{{ marks.internal_marks }}</td>
                <td>{{ marks.external_marks }}</td>
                <td>{{ marks.total_marks }}</td>
                <td>{{ marks.result }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/PlacementPortal/queried_list.html
{% extends "base.html" %}

{% block content %}
    <br>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>H.T.No</th>
            <th>Department</th>
            <th>D.O.B</th>
            <th>Gender</th>
            <th>Caste</th>
            <th>Tenth%</th>
            <th>Inter%</th>
            <th>BTech%</th>
            <th>Backlogs</th>
        </tr>
        </thead>
        {% for student in student_list %}
            <tr>
                <td>{{ student.pk }}</td>
                <td>
                    {{ student.first_name }}  {{ student.last_name }}
                </td>
                <td>{{ student.hall_ticket_number }}</td>
                <td>{{ student.department__acronym }}</td>
                <td>{{ student.date_of_birth }}</td>
                {% if student.gender == True %}
                    <td>Male</td>
                {% else %}
                    <td>Female</td>
                {% endif %}
                <td>{{ student.caste }}</td>
                <td>{{ student.tenth_marks }}</td>
                <td>{{ student.inter_marks }}</td>
                <td>{{ student.btech_marks }}</td>
                <td>{{ student.backlogs }}</td>


            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/PlacementPortal/query.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Student List</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
        <style>

            #id_gender li,#id_caste li,#id_department li{
                display: inline;
                text-decoration: none;
                margin: 5px;

            }

            #id_gender, #id_caste,#id_department{
                display: inline;
                margin: 0px;
            }

            .content{
                align-content: center;
                align-items: center;

            }

            .jumbotron{
                margin-top: 100px;
            }


        </style>

    </head>
    <body>
    <div class="container">
        <div class="jumbotron">
            <form  method = "POST">
                {% csrf_token %}
                <div class="main-container">
                    <div class="content">
                        <label id="gender">Gender <span>{{ form.gender }}</span>
                        </label>
                    </div>
                <div>
                    <label id="caste">Caste <span>{{ form.caste }}</span>
                    </label>
                </div>
                <div>
                    <label id="department">Department <span>{{ form.department }}</span>
                    </label>
                </div>
                <div>
                    <label id="tenth">Tenth Marks<span id="span_tenth">{{ form.tenth }}</span>
                    </label>
                </div>
                <div>
                    <label id="inter">Inter Marks<span id="span_inter">{{ form.inter }}</span>
                    </label>
                </div>
                <div>
                    <label id="btech">B.Tech Marks<span id="span_btech">{{ form.btech }}</span>
                    </label>
                </div>
                <div>
                    <label id="backlogs">Backlogs<span id="span_backlogs">{{ form.backlogs }}</span>
                    </label>
                </div>

             <input type="submit" class="btn btn-success" value = "Get Students"/>
                </div>

         </form>
        </div>
    </div>
    </body>
</html>

templates/PlacementPortal/query_form.html
<head>
        <meta charset="UTF-8">
        <title>Student List</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
        <style>

            #id_gender li,#id_caste li,#id_department li{
                display: inline;
                text-decoration: none;
                margin: 5px;

            }

            #id_gender, #id_caste,#id_department{
                display: inline;
                margin: 0px;
            }

            .content{
                align-content: center;
                align-items: center;

            }

            .jumbotron{
                margin-top: 50px;
            }


        </style>

    </head>

{% extends "base.html" %}

{% block content %}
<div class="container">
        <div class="jumbotron">
            <form  method = "POST">
                {% csrf_token %}
                <div class="main-container">
                    <div class="content">
                        <label id="gender">Gender <span>{{ form.gender }}</span>
                        </label>
                    </div>
                <div>
                    <label id="caste">Caste <span>{{ form.caste }}</span>
                    </label>
                </div>
                <div>
                    <label id="department">Department <span>{{ form.department }}</span>
                    </label>
                </div>
                <div>
                    <label id="tenth">Tenth Marks<span id="span_tenth">{{ form.tenth }}</span>
                    </label>
                </div>
                <div>
                    <label id="inter">Inter Marks<span id="span_inter">{{ form.inter }}</span>
                    </label>
                </div>
                <div>
                    <label id="btech">B.Tech Marks<span id="span_btech">{{ form.btech }}</span>
                    </label>
                </div>
                <div>
                    <label id="backlogs">Backlogs<span id="span_backlogs">{{ form.backlogs }}</span>
                    </label>
                </div>

             <input type="submit" class="btn btn-success" value = "Get Students"/>
                </div>

         </form>
        </div>
    </div>
{%  endblock %}

templates/PlacementPortal/student_form.html
{% extends 'base.html' %}
{% include 'style.css' %}
{% block content %}
    <br>
    <form action="" method="POST" class="form-control">
        {% csrf_token %}

        {{ student_form.as_p }}
        {{ contact_form.as_p }}
        <br>
        <input class="btn-default" type="submit" value="Submit"/>
    </form>
{% endblock content%}

templates/PlacementPortal/student_list.html
{% extends "base.html" %}

{% block content %}
    <br>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>H.T.No</th>
            <th>Department</th>
            <th>D.O.B</th>
            <th>Gender</th>
            <th>Caste</th>
            <th>Tenth%</th>
            <th>Inter%</th>
            <th>BTech%</th>
            <th>Backlogs</th>
            <th>Contact</th>
            <th>Actions</th>
        </tr>
        </thead>
        {% for student in student_list %}
            <tr>
                <td>{{ student.id }}</td>
                <td>
                    <a href="{% url 'PlacementPortal:student_marks' dept_id=student.department_id pk=student.id %}">{{ student.full_name }}</a>
                </td>
                <td>{{ student.hall_ticket_number }}</td>
                <td>{{ student.department__acronym }}</td>
                <td>{{ student.date_of_birth }}</td>
                {% if student.gender == True %}
                    <td>Male</td>
                {% else %}
                    <td>Female</td>
                {% endif %}
                <td>{{ student.caste }}</td>
                <td>{{ student.tenth_marks }}</td>
                <td>{{ student.inter_marks }}</td>
                <td>{{ student.btech_marks }}</td>
                <td>{{ student.backlogs }}</td>
                <td>
                    <a href="{% url 'PlacementPortal:student_contact' dept_id=student.department_id pk=student.id %}">Contact</a>
                </td>
                <td><a href="{% url 'PlacementPortal:department_student_edit' dept_id=student.department_id pk=student.id %}">Edit</a></td>

            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/PlacementPortal/upload.html


{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="jumbotron">
    <h3>{{title}}</h3>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
        {{ form.as_ul }}
        <br>
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
    </div>

{% endblock content %}