PlacementPortal/urls.py
from django.urls import path
from .views import *
from .api import *

app_name = "PlacementPortal"

urlpatterns = [

    path('login/', LoginUser.as_view(), name="login_url"),
    path('logout/', logout_user, name="logout"),

    path('department/<int:dept_id>/student/<int:pk>/marks/', MarkList.as_view(), name="student_marks"),
    path('department/<int:dept_id>/student/<int:pk>/contact/', ContactDetail.as_view(), name="student_contact"),

    path('department/', DepartmentList.as_view(), name="department_list"),
    path('department/<int:dept_id>/student/', DepartmentStudentList.as_view(), name="department_student_list"),
    path('department/<int:dept_id>/student/<int:pk>/edit', DepartmentStudentEdit.as_view(),
         name="department_student_edit"),
    path('department/<int:pk>/delete/', DepartmentDelete.as_view(), name="department_delete"),
    path('department/<int:pk>/edit/', DepartmentUpdate.as_view(), name="department_update"),
    path('department/add/', DepartmentCreate.as_view(), name="department_add"),

    path('home/', Home.as_view(), name="home"),
    path('', LoginUser.as_view(), name="login"),

    path('studentUpload/', studentUpload, name="student_file_upload"),
    path('marksUpload/', marksUpload, name="marks_file_upload"),
    path('query/', QueryDb.as_view(), name='select_query'),



    # api urls
    path('api/', StudentListView.as_view(), name="api_student_list"),
    path('api/<str:htno>/', StudentDetailView.as_view(), name="api_student_detail"),
]



agi-demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("PlacementPortal.urls")),
    path('studentPortal/', TemplateView.as_view(template_name="StudentPortal/index.html")),
]

templates/snippets/navbar.html
<nav class="navbar navbar-dark bg-primary">
    <a href="/" class="navbar-brand mb-0 h1">AGI</a>
    {% if request.user.is_authenticated %}
        <span class="navbar-brand mb-0 h1" style="align-content: right;">
            <a href="{% url 'PlacementPortal:logout' %}" style="color: #ffffff;">LOGOUT</a>
        </span>
    {% else %}
        <span class="navbar-brand mb-0 h1" style="align-content: right;">X</span>
    {% endif %}
</nav>

templates/snippets/toobar.html
<head>
    <style>
        li {
            margin: 0 10px;
        }
    </style>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand mb-0 h3" href="#">Menu</a>
        </div>


        <ul class="nav navbar-nav h5 navbar-right" style="align-content: right;">
            <li><a href="{% url 'PlacementPortal:department_list' %}">Departments</a></li>
            <li><a href="{% url 'PlacementPortal:student_file_upload' %}">StudentUpload</a></li>
            <li><a href="{% url 'PlacementPortal:marks_file_upload' %}">MarksUpload</a></li>
            <li><a href="{% url 'PlacementPortal:select_query' %}">QueryStudents</a></li>
        </ul>
    </div>
</nav>
